# Generated by Django 3.2.9 on 2021-11-30 02:50

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211130_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name_kana',
            field=models.CharField(max_length=150, verbose_name='名（かな）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name_kana',
            field=models.CharField(max_length=150, verbose_name='姓（かな）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='01', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
